version: "3.0"
services:
  php-fpm:
    build:
      context: ./config/php-fpm
      dockerfile: ./Dockerfile
    volumes:
      - "${PROJECT_ROOT_DIRECTORY:-.}:/var/www"
    depends_on:
      - rabbitmq
    env_file:
      - .env
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./data/mnesia:/var/lib/rabbitmq/mnesia"